# vi: ts=2 sw=2 et nu
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$fill\
$line_break$nix_shell$aws$character
"""
right_format = '$all'

[profiles]
transient = "$directory$nix_shell$aws$character"

[fill]
symbol = ''

[character]
format = "$symbol "
# success_symbol = '[»](bold green)'
# success_symbol = '[󱞵](bold green)'
success_symbol = '[](bold green)'

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "󰘬 "
style = "bold purple"

[git_commit]
commit_hash_length = 12
only_detached = false

# [git_metrics]
# added_style = 'bold blue'
# format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
# disabled = false

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "red bold"
stashed = '[*$count](blue)'
ahead = "[↑$count](green)"
behind = "[↓$count](green)"
up_to_date = ""
diverged = "[󰓢 ](red)"
conflicted = "[~$count](red)"
deleted = "[✘$count](red)"
renamed = "[»$count](blue)"
modified = "[‼$count](yellow)"
staged = "[+$count](bold blue)"
untracked = "[?$count](bright-blue)"
typechanged = ""
ignore_submodules = false
disabled = false

[aws]
format = '[$symbol($profile)(\[$duration\]) ]($style)'
symbol = '󰸏 '

[bun]
format = "[$symbol($version )]($style)"

[c]
format = "[$symbol($version(-$name) )]($style)"

[cmake]
format = "[$symbol($version )]($style)"

[cobol]
format = "[$symbol($version )]($style)"

[conda]
format = "[$symbol$environment]($style) "

[crystal]
format = "[$symbol($version )]($style)"

[daml]
format = "[$symbol($version )]($style)"

[dart]
format = "[$symbol($version )]($style)"

[deno]
format = "[$symbol($version )]($style)"

[docker_context]
disabled = true
format = "[$symbol$context]($style) "
symbol = "󰡨 "

[dotnet]
format = "[$symbol($version )(󰣉 $tfm )]($style)"

[elixir]
format = '[$symbol($version \(OTP $otp_version\) )]($style)'

[elm]
format = "[$symbol($version )]($style)"

[erlang]
format = "[$symbol($version )]($style)"

[fennel]
format = "[$symbol($version )]($style)"

[gleam]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"

[gradle]
format = "[$symbol($version )]($style)"

[guix_shell]
format = "[$symbol]($style) "

[haskell]
format = "[$symbol($version )]($style)"

[haxe]
format = "[$symbol($version )]($style)"

[helm]
format = "[$symbol($version )]($style)"

[java]
format = "[$symbol($version )]($style)"

[julia]
format = "[$symbol($version )]($style)"

[kotlin]
format = "[$symbol($version )]($style)"

[lua]
format = "[$symbol($version )]($style)"

[memory_usage]
format = "$symbol[$ram( | $swap)]($style) "

[meson]
format = "[$symbol$project]($style) "

[nim]
format = "[$symbol($version )]($style)"

[nix_shell]
format = '[$symbol$state(\($name\))]($style) '
impure_msg = '󰼩 '
pure_msg = "󱄅 "
symbol = ""
style = "#90c1ea"

[nodejs]
format = "[$symbol($version )]($style)"

[ocaml]
format = '[$symbol($version )(\($switch_indicator$switch_name\) )]($style)'

[odin]
format = "[$symbol($version )]($style)"

[opa]
format = "[$symbol($version )]($style)"

[perl]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[pulumi]
format = "[$symbol($username@)$stack]($style) "

[purescript]
format = "[$symbol($version )]($style)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[quarto]
format = "[$symbol($version )]($style)"

[raku]
format = "[$symbol($version-$vm_version )]($style)"

[red]
format = "[$symbol($version )]($style)"

[rlang]
format = "[$symbol($version )]($style)"

[ruby]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol($version )]($style)"

[scala]
format = "[$symbol($version )]($style)"

[solidity]
format = "[$symbol($version)]($style)"

[spack]
format = "[$symbol$environment]($style) "

[swift]
format = "[$symbol($version )]($style)"

[terraform]
format = "[$symbol$workspace]($style) "

[typst]
format = "[$symbol($version )]($style)"

[vagrant]
format = "[$symbol($version )]($style)"

[vlang]
format = "[$symbol($version )]($style)"

[zig]
format = "[$symbol($version )]($style)"

